### ISSUE TITLE
Empty ContextMenu causes a JavaScript error

### ISSUE THREAD

**Issue by OlliTietavainenVaadin** [vaadin/vaadin-context-menu-flow#62] opened 2019-04-04 10:03 UTC
`<vaadin.version>13.0.1</vaadin.version>`
Creating an empty context menu causes a JavaScript error when clicking:
```
        TextField textField = new TextField();
        ContextMenu contextMenu = new ContextMenu();
        contextMenu.setTarget(textField);
```
Clicking the TextField shows a `TypeError` in the browser.

**Comment by pekam** [comment] 2019-06-06 08:03
Duplicate of https://github.com/vaadin/vaadin-context-menu/issues/227
Fixed in v14

**Closed as completed by pekam** 2019-06-06 08:03 UTC
